setup:
  image: cockroachdb/cockroach:v1.0.1
  command:
    - sh
    - -c
    - exec /cockroach/cockroach sql -e 'CREATE USER roach; CREATE DATABASE roach; GRANT ALL ON DATABASE roach TO roach'
  startDeploymentTimeoutSeconds: 120
  env:
    - name: COCKROACH_HOST
      value: cockroachdb
    - name: COCKROACH_INSECURE
      value: true
services:
  cockroachdb:
    image: cockroachdb/cockroach:v1.0.1
    command:
      - /cockroach/cockroach
      - start
      - --insecure
    ports:
      - 26257:26257
      - 8181:8080
    readinessProbe:
      command:
        - sh
        - -c
        - exec /cockroach/cockroach sql --insecure -e 'select 1;'
      periodSeconds: 5
      startDeploymentTimeoutSeconds: 120
